name: Build Pull Request Godot Editor

on:
  [pull_request]

jobs:
  generate-build:
    name: Generate Build of Pull Request
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0


    - name: Define Godot version based on branch name
      run: |
        GODOT_VERSION="${{ github.base_ref }}"

        if [ "${{ github.base_ref }}" = "master" ]; then
          GODOT_VERSION=4
        elif [ "${{ github.base_ref }}" = "godot3" ]; then
          GODOT_VERSION=3
        fi

        echo "GODOT_VERSION=${GODOT_VERSION}" >> $GITHUB_ENV
        echo "TAG_PREFIX=godot${GODOT_VERSION}-" >> $GITHUB_ENV

    - name: Get plugin version
      uses: paulhatch/semantic-version@v5.0.0
      id: version
      with:
        tag_prefix: "${{env.TAG_PREFIX}}v"
        major_pattern: "BREAKING CHANGE:"
        minor_pattern: "feat:"
        version_format: "v${major}.${minor}.${patch}-alpha.${increment}"

    - name: Change version
      run: |
        REGEX_FIND_VERSION_TO_CHANGE_CONTENT_MD_FILE='(?<=version=")[^"]+'

        perl -pi -e "s/$REGEX_FIND_VERSION_TO_CHANGE_CONTENT_MD_FILE/${{env.TAG_PREFIX}}${{ steps.version.outputs.version }}/g" addons/admob/plugin.cfg

    - name: Compress .zip
      run: |
        git archive --format=zip --output compress.zip `git stash create`

    - name: Uncompress .zip to Artifact
      run: |
        unzip compress.zip -d zip_extract_folder/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: godot-${{env.GODOT_VERSION}}-admob-editor-${{ steps.version.outputs.version }}
        path: zip_extract_folder/